stages:
  - force_push_to_github

variables:
  GITHUB_REPO_URL: "https://github.com/nesi/agdr-validator.git"
  GIT_TAG: "v1.3"

force_push_to_github:
  stage: force_push_to_github
  script:
    - chmod +x copy_and_tag_to_github.sh
    - ./copy_and_tag_to_github.sh $GITHUB_REPO_URL $GIT_TAG
  when: manual