import datetime 

# Project Info:
ProjectInfo = [
    ['Allopatric speciation in the bacterial phylum Aquificota enables genus-level endemism in Aotearoa-New Zealand', '2012-2017', 'Allopatric speciation has been difficult to examine among microorganisms, with prior reports of endemism restricted to sub-genus level taxa. Here, we present evidence of an endemic bacterial genus, Venenivibrio (phylum Aquificota), from the Taupō Volcanic Zone (TVZ), Aotearoa-New Zealand. 16S rRNA gene sequencing revealed widespread distribution of Venenivibrio in TVZ geothermal springs (74 %, n=686), with maximal read abundance occurring at pH 4-6, 50-70 °C, and low oxidation-reduction potentials. Genomic analysis and culture-based experiments of the only characterised species for the genus, Venenivibrio stagnispumantis CP.B2T, confirmed a chemolithoautotrophic metabolism dependent on hydrogen oxidation, further highlighting a specific environmental niche that could enhance habitat isolation. While similarity between Venenivibrio populations illustrated dispersal is not limited across the TVZ, extensive amplicon, metagenomic, and phylogenomic analyses of global microbial communities from DNA sequence databases indicates Venenivibrio is geographically restricted to the Aotearoa-New Zealand archipelago. We conclude that combined geographical and physicochemical constraints have resulted in the establishment of an endemic bacterial genus.', 'University of Canterbury', 'Assoc Prof Matthew Stott', 'matthew.stott@canterbury.ac.nz', 'Unknown'],
    [None, None, 'Data stored in this repository contains 10 metagenomic samples (raw) and four metagenome-assembled genomes (MAGs; processed) analysed and created for this study, respectively. All metagenomic samples and MAGs are from the microbial communities of geothermal features in the Taupō Volcanic Zone (TVZ), Aotearoa-New Zealand.', None, None, None, None]
]

# Experiment and sample info:
Experiments = [
    ['NZ_GEOTHERMAL_METAGENOMES_01', 'NZ_GEOTHERMAL_MAGS_01', 'FASTQ files of 10 samples from WGS', '10 metagenomic samples from the microbial communities of geothermal features in the TVZ, Aotearoa-New Zealand', 'Searching for the presence of Venenivibrio sp.', 'Currently unpublished', 'Environmental', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['NZ_GEOTHERMAL_MAGS_01', 'NZ_GEOTHERMAL_METAGENOMES_01', 'FASTA files of 4 metagenome-assembed genomes', '4 MAGs assembled from metagenomic samples of TVZ geothermal features that classified to Venenivibrio sp.', 'Sequence similarity to Venenivibrio stagnispumantis CP.B2', 'Currently unpublished', 'Environmental', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
]


Environmental = [
    ['AP', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2012, 7, 1, 0, 0), 'Aerobic', '50 mL PP Falcon tube', 'Katrin Hug', 'None', 'Unknown', 'Unknown', 'Frozen -80C', 'Unknown', "Artist's Palette, Waiotapu, Taupō Volcanic Zone", 'Metagenome', 6.9, 45, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['CPc', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2012, 7, 1, 0, 0), 'Aerobic', '50 mL PP Falcon tube', 'Katrin Hug', 'None', 'Unknown', 'Unknown', 'Frozen -80C', 'Unknown', 'Champagne Pool, Waiotapu, Taupō Volcanic Zone', 'Metagenome', 5.8, 75, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['CPp', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2012, 7, 1, 0, 0), 'Aerobic', '5000 mL PP vessel', 'Katrin Hug', 'Filtered through a 0.22 micron cellulose membrane filter', '500 mL', 'Unknown', 'Frozen -80C', 'Unknown', 'Champagne Pool, Waiotapu, Taupō Volcanic Zone', 'Metagenome', 5.5, 75, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['CPr', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2012, 7, 1, 0, 0), 'Aerobic', '50 mL PP Falcon tube', 'Katrin Hug', 'None', 'Unknown', 'Unknown', 'Frozen -80C', 'Unknown', 'Champagne Pool, Waiotapu, Taupō Volcanic Zone', 'Metagenome', 5.5, 68, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['IMP.14_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2017, 2, 23, 0, 0), 'Aerobic', '250 mL PP Corning tube', 'Matthew Stott', 'None', 'Unknown', 'Unknown', 'Frozen -20C', 'Unknown', "Fred & Maggie's Pool, Orakei-Korako, Taupō Volcanic Zone", 'Metagenome', 6.9, 96.4, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['IMP.15_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2017, 2, 23, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Matthew Stott', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', "Fred & Maggie's Pool, Orakei-Korako, Taupō Volcanic Zone", 'Metagenome', 6.9, 96.4, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P1.0037_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2013, 8, 30, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Jean Power', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', 'Inferno Crater Lake, Waimangu, Taupō Volcanic Zone', 'Metagenome', 2.4, 41, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P1.0103_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2013, 10, 10, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Jean Power', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', 'Inferno Crater Lake, Waimangu, Taupō Volcanic Zone', 'Metagenome', 2.4, 55.1, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P1.0108_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2013, 10, 18, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Jean Power', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', 'Inferno Crater Lake, Waimangu, Taupō Volcanic Zone', 'Metagenome', 2.6, 69.1, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P2.0050_MG', 'NZ_GEOTHERMAL_METAGENOMES_01', False, 'Not applicable', 'Not applicable', 'MaterialSample', 'Hot springs metagenome [NCBI:txid433727]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2016, 8, 2, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Jean Power', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', 'Whakarewarewa Feature 51, Rotorua, Taupō Volcanic Zone', 'Metagenome', 3, 60, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['CPp_MAG1', 'NZ_GEOTHERMAL_MAGS_01', False, 'Not applicable', 'Not applicable', 'Taxon', 'Venenivibrio sp. [NCBI:txid407997]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2012, 7, 1, 0, 0), 'Aerobic', '5000 mL PP vessel', 'Katrin Hug', 'Filtered through a 0.22 micron cellulose membrane filter', '500 mL', 'Unknown', 'Frozen -80C', 'Unknown', 'Champagne Pool, Waiotapu, Taupō Volcanic Zone', 'Metagenome-assembled genome', 5.5, 75, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['NZ1_MAG2', 'NZ_GEOTHERMAL_MAGS_01', 'GOLD Analysis ID: Ga0079637', 'GOLD Project ID: Gp0119888', 'GOLD Biosample ID: Gb0119300', 'Taxon', 'Venenivibrio sp. [NCBI:txid407997]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', 'Unknown', 'Aerobic', 'Unknown', 'Anna-Louise Reysenbach', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Waiotapu No.15 Feature 1, Waiotapu, Taupō Volcanic Zone', 'Metagenome-assembled genome', 4.5, 74, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P1.0019_MAG3', 'NZ_GEOTHERMAL_MAGS_01', 'SRA Run Accession: SRR14702244', 'PRJNA417281', 'SAMN08011025', 'Taxon', 'Venenivibrio sp. [NCBI:txid407997]', 'Geothermal spring sediment', 'sediment [ENVO:00002007]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2013, 8, 14, 0, 0), 'Aerobic', '15 mL PP Falcon tube', 'Jean Power', 'Cryopreserved in 1X TE pH 8.0, molecular grade water and glycerol (1:3:5 ratio)', '~1.5 mL sediment with 15 mL cryopreservant', 'Unknown', 'Frozen -20C', 'Unknown', 'Radiata Pool, Ngatamariki, Taupō Volcanic Zone', 'Metagenome-assembled genome', 7.49, 63.3, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['P2.0050_MAG4', 'NZ_GEOTHERMAL_MAGS_01', False, 'Not applicable', 'Not applicable', 'Taxon', 'Venenivibrio sp. [NCBI:txid407997]', 'Geothermal spring water', 'liquid water [ENVO:00002006]', 'geothermally active field [ENVO:01001851] | hot spring [ENVO:00000051]', 'New Zealand: Taupō Volcanic Zone', 'Restricted', datetime.datetime(2016, 8, 2, 0, 0), 'Aerobic', '500 mL PP Nalgene bottle', 'Jean Power', 'Filtered through a Sterivex-GP 0.22 micron PES column filter', '2000 mL', 'Unknown', 'Frozen -20C', 'Unknown', 'Whakarewarewa Feature 51, Rotorua, Taupō Volcanic Zone', 'Metagenome-assembled genome', 3, 60, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
]

# Files and Instruments:

Files = [
    ['38c8388aeb4931c923007dc4d328401c', 863297000, 'AP_S4_L001_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'AP', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['4760a271ee04864a3026cdcdd846735d', 991764000, 'AP_S4_L001_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'AP', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['678e96d2f1b181ef5aab657cc4b3c70d', 639376000, 'CPc_S2_L001_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPc', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['ce04d8e6faa224eddb85a39e9df0d3d8', 661182000, 'CPc_S2_L001_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPc', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['e50b1e5139a74d778380a270e715ee5f', 695313000, 'CPp_S1_L001_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPp', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['43a05659beb76f60f6c1c0053d640bed', 673066000, 'CPp_S1_L001_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPp', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['0964ee0ad8ed1fa8ce982b827c898f59', 569418000, 'CPr_S3_L001_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPr', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['27069e7d590bfc98c3a5f4b599fc4490', 648299000, 'CPr_S3_L001_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'CPr', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['03fe061e23d1604794ef47d573c823ba', 1442189000, 'CBBWRANXX-2251-09-25-01_S21_L003_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.14_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['5892820bc3cd8540466eaad2fc4c2e92', 1495057000, 'CBBWRANXX-2251-09-25-01_S21_L003_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.14_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['4b21e72a8a78031ab655188d899e0af0', 1360203000, 'CBBWRANXX-2251-09-25-01_S21_L004_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.14_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['755481006aceadd62a3f461066720038', 1409378000, 'CBBWRANXX-2251-09-25-01_S21_L004_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.14_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['5403797173ef3f01d1442c08b95f16a2', 1641705000, 'CBBWRANXX-2251-10-25-01_S22_L003_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.15_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['3d669fc0e0486bd69650230fd2fbc735', 1700515000, 'CBBWRANXX-2251-10-25-01_S22_L003_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.15_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['6a730244d2fe58f5d22668d82a519efc', 1549424000, 'CBBWRANXX-2251-10-25-01_S22_L004_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.15_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['93dd92475069c3d1ac1714b1733e89e6', 1603226000, 'CBBWRANXX-2251-10-25-01_S22_L004_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'IMP.15_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['90bea49a58a30fd5e3a173cdc649b346', 1442752000, 'CBBWRANXX-2251-01-25-01_S13_L003_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0037_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['9d46d7b8f86936419be2c8cb80de43ae', 1470176000, 'CBBWRANXX-2251-01-25-01_S13_L003_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0037_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['e88f9c4ccf1ffd1b56774fde46d39787', 1352829000, 'CBBWRANXX-2251-01-25-01_S13_L004_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0037_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['e197de6832c5da4c186eac2d19983ab0', 1377500000, 'CBBWRANXX-2251-01-25-01_S13_L004_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0037_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['a4e32afcf33904ea476a0b5ab322ebae', 1656745000, 'CBBWRANXX-2251-02-25-01_S14_L003_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0103_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], 
    ['a626b7980a59da3b91b04524d299a8a1', 1685018000, 'CBBWRANXX-2251-02-25-01_S14_L003_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0103_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['30a228a766b0e48786fc488d768f8199', 1543242000, 'CBBWRANXX-2251-02-25-01_S14_L004_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0103_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['d7c5e94204a222e766a14a2dbf11275e', 1569756000, 'CBBWRANXX-2251-02-25-01_S14_L004_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0103_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['539a21c29ecf21fe344274eacde47bb4', 1411478000, 'CBBWRANXX-2251-03-25-01_S15_L003_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0108_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['a13ba861fc859e43be13f4e0d7b0539f', 1429384000, 'CBBWRANXX-2251-03-25-01_S15_L003_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0108_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['b3128358c69b04ac377b1e3dcea9c044', 1310618000, 'CBBWRANXX-2251-03-25-01_S15_L004_R1_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0108_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['415b6f34214007e76e10c907a2793825', 1327312000, 'CBBWRANXX-2251-03-25-01_S15_L004_R2_001.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P1.0108_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['507331c7f4cd8e89a93120d0b44fae13', 405888000, 'P2.0050_MG_161019.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P2.0050_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['5b65ed8e59045ecd96e9222289058924', 991173000, 'P2.0050_MG_161101.fastq.gz', 'WGS', 'Unaligned Reads', 'FASTQ', 'Raw Sequencing Data', 'P2.0050_MG', 'Not applicable', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['57fd5837f37f9072fdc3e0b586ac14ca', 1487000, 'CPp_MAG1.fasta', 'MAG', 'Assembled Reads', 'FASTA', 'Sequencing Data', 'CPp_MAG1', 'ALTAS v2.6a3 workflow, CheckM v1.0.5', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['821086f91fb6dd50f759e6740109e501', 1468000, 'NZ1_MAG2.fasta', 'MAG', 'Assembled Reads', 'FASTA', 'Sequencing Data', 'NZ1_MAG2', 'ALTAS v2.6a3 workflow, CheckM v1.0.5', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['abffbe53636f6e465a5cd7f2101fe75c', 1311000, 'P1.0019_MAG3.fasta', 'MAG', 'Assembled Reads', 'FASTA', 'Sequencing Data', 'P1.0019_MAG3', 'ALTAS v2.6a3 workflow, CheckM v1.0.5', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    ['9a2aaaaea667e3110e1e4cdc8f643aea', 1979000, 'P2.0050_MAG4.fasta', 'MAG', 'Assembled Reads', 'FASTA', 'Sequencing Data', 'P2.0050_MAG4', 'MEGAHIT v1.2.9, MetaBAT 2 v2.10, CheckM v1.0.5', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
]

# Instrument Metadata
InstrumentMetadata = [
    ['AP', 'Illumina MiSeq', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'MiSeq', 'Yes', 'AP_S4', 'Unknown', 'Illumina MiSeq reagent kit v2 (500 cycle)', 'Illumina', 'v2', 'Random', 'Unknown', 'WGS', 'Unknown', 'Unknown', 'Peter Doherty Institute for Infection and Immunity, University of Melbourne', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['CPc', 'Illumina MiSeq', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'MiSeq', 'Yes', 'CPc_S2', 'Unknown', 'Illumina MiSeq reagent kit v2 (500 cycle)', 'Illumina', 'v2', 'Random', 'Unknown', 'WGS', 'Unknown', 'Unknown', 'Peter Doherty Institute for Infection and Immunity, University of Melbourne', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['CPp', 'Illumina MiSeq', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'MiSeq', 'Yes', 'CPp_S1', 'Unknown', 'Illumina MiSeq reagent kit v2 (500 cycle)', 'Illumina', 'v2', 'Random', 'Unknown', 'WGS', 'Unknown', 'Unknown', 'Peter Doherty Institute for Infection and Immunity, University of Melbourne', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['CPr', 'Illumina MiSeq', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'MiSeq', 'Yes', 'CPr_S3', 'Unknown', 'Illumina MiSeq reagent kit v2 (500 cycle)', 'Illumina', 'v2', 'Random', 'Unknown', 'WGS', 'Unknown', 'Unknown', 'Peter Doherty Institute for Infection and Immunity, University of Melbourne', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['IMP.14_MG', 'Illumina HiSeq 2500', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'HiSeq 2500 v4', 'Yes', datetime.datetime(2251, 9, 1, 0, 0), 'Unknown', 'ThruPLEX DNA-Seq kit', 'Takara Bio', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '2x125 bp', 'University of Otago', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['IMP.15_MG', 'Illumina HiSeq 2500', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'HiSeq 2500 v4', 'Yes', datetime.datetime(2251, 10, 1, 0, 0), 'Unknown', 'ThruPLEX DNA-Seq kit', 'Takara Bio', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '2x125 bp', 'University of Otago', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['P1.0037_MG', 'Illumina HiSeq 2500', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'HiSeq 2500 v4', 'Yes', datetime.datetime(2251, 1, 1, 0, 0), 'Unknown', 'ThruPLEX DNA-Seq kit', 'Takara Bio', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '2x125 bp', 'University of Otago', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['P1.0103_MG', 'Illumina HiSeq 2500', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'HiSeq 2500 v4', 'Yes', datetime.datetime(2251, 2, 1, 0, 0), 'Unknown', 'ThruPLEX DNA-Seq kit', 'Takara Bio', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '2x125 bp', 'University of Otago', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['P1.0108_MG', 'Illumina HiSeq 2500', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'HiSeq 2500 v4', 'Yes', datetime.datetime(2251, 3, 1, 0, 0), 'Unknown', 'ThruPLEX DNA-Seq kit', 'Takara Bio', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '2x125 bp', 'University of Otago', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    ['P2.0050_MG', 'Ion Torrent PGM System for NGS', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Ion 318 Chip Kit v2 for Ion PGM system', 'No', 'P2.0050_161019, P2.0050_161101', 'Unknown', 'Ion PGM Template IA 500 preparation kit, Ion PGM Hi-Q View sequencing kit', 'ThermoFisher Scientific', 'Unknown', 'Random', 'Unknown', 'WGS', 'Unknown', '1x400 bp', 'University of Waikato', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown']
]